dist: xenial
language: node_js
node_js:
  - "10"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - npm install -g ionic

script:
  - npm run build
  - npm run test:ci
  - npm run lint
