language: node_js
node_js:
  - "10"

apt:
  chrome: stable

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g ionic

script:
  - npm run build
  - npm run test -- --watch=false
  - npm run lint
